# Generated by Django 5.2 on 2025-04-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_low'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_high',
            name='importance',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='High', max_length=10, null=True),
        ),
    ]
