# Generated by Django 5.2 on 2025-04-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_high_importance'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_medium',
            name='importance',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10, null=True),
        ),
    ]
