# Generated by Django 5.2 on 2025-04-10 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_medium_importance'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_low',
            name='importance',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10, null=True),
        ),
    ]
