# Generated by Django 5.2 on 2025-04-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_low_importance'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_low',
            name='estimated_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
