# Generated by Django 5.2 on 2025-04-10 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_task_low_estimated_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_low',
            name='estimated_minutes',
        ),
    ]
