# Generated by Django 5.2 on 2025-04-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_remove_task_low_estimated_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_low',
            name='estimated_minutes',
            field=models.IntegerField(default=30),
        ),
    ]
